Adding the project assingment for the internship interview for python data engineer
wealth42/nick-fury pull request #10
Opened 2020-06-26 08:06 UTC by harsh07021999

First submission

2020-06-26 14:51 UTC, dwividha requested changes

2020-06-26 14:51 UTC, dashu2410 commented on Python_DataEngineering/README.md
> + Python Libraries :- Pandas,Schedule,Json,Requests,MySQL-connector-python
Best practice is to make a requirements.txt file from which you can directly install all dependencies.
You can do this with `pip freeze> requirements.txt` from inside your virtualenv

2020-06-26 14:51 UTC, dashu2410 commented on Python_DataEngineering/Initialize_database.py
> +database = mysql.connect(user='root', password='password',host='localhost')
You should keep your DB secrets in your environment variables

2020-06-26 14:51 UTC, dashu2410 commented on Python_DataEngineering/Project_nick-fury.py
> +        data4=[]
rather than naming data1, data2, etc. its better to name things in a more readable way - like nb_bikes_arr, nb_docks_arr etc

2020-06-26 14:51 UTC, dashu2410 commented on Python_DataEngineering/Project_nick-fury.py
> +            cursor.execute("insert into data values(" +"\""  + str(row['id']) + "\"" + "," + "\"" + str(row['commonName']) + "\"" + "," + str(row['lat']) + "," + str(row['lon']) + "," + "\"" + str(ro
can you make this a formatted string instead? This string would be very difficult to debug in case an error occurs

2020-06-27 12:50 UTC, harsh07021999 commented
Sir please review the changes made as requested by you.

2020-06-30 05:01 UTC, dashu2410 commented
Closing the Pull Request

2020-06-30 05:01 UTC, closed without merging