Python - Data Engineer Assignment for Internship at Wealth42
wealth42/nick-fury pull request #11
Opened 2020-06-26 08:07 UTC by namangulati22

2020-06-26 15:52 UTC, dwividha requested changes
Hi @namangulati22 
Thanks for attempting the assignment! However, there is an error in the understanding of the requirements that were given. We'll be happy to reconsider if you can identify and fix the error and re-submit the requested changes.

2020-06-26 15:52 UTC, dashu2410 commented on bikepoint.py
> +                val_addon = tuple(final_addon_data.values())
This is not a good approach - this is not validating the order in which the tuple is generated

2020-06-26 15:52 UTC, dashu2410 commented on DDL.sql
> +CREATE TABLE IF NOT EXISTS `addons` (
Since you have already stored the data for bike availability in the 'point' table, this table might be redundant.

2020-06-26 15:52 UTC, dashu2410 commented on bikepoint.py
> +def looper():
Try replacing this with crontab instead

2020-06-26 15:52 UTC, dashu2410 commented on query.py
> +        querry='SELECT * FROM bikepoint.point where commonName like \'%{query}%\';'
Avoid using incorrect and ambiguous spellings - creates space for very difficult to find problems later

2020-06-27 11:40 UTC, namangulati22 commented
Sir/ma'am,
Thank you for pointing this out. I will get started with this and will
submit with corrections as soon as possible.
Thank you

On Fri, Jun 26, 2020, 9:22 PM dashu2410 <notifications@github.com> wrote:

> *@dashu2410* requested changes on this pull request.
>
> Hi @namangulati22 <https://github.com/namangulati22>
> Thanks for attempting the assignment! However, there is an error in the
> understanding of the requirements that were given. We'll be happy to
> reconsider if you can identify and fix the error and re-submit the
> requested changes.
> ------------------------------
>
> In bikepoint.py
> <https://github.com/wealth42/nick-fury/pull/11#discussion_r446261044>:
>
> > +
> +            additional_properties = (final_point_data.pop('additionalProperties')[1:-2].split('}, '))
> +
> +            final_point_data.pop('$type')
> +            for addon in additional_properties:
> +                final_addon_data = dict()
> +                final_addon_data['id'] = final_point_data['id']
> +                data = json.loads(addon + '}')
> +                for key in data:
> +                    final_addon_data[key] = data[key]
> +
> +                final_addon_data.pop('$type')
> +                if data['key'] == 'NbDocks': final_point_data['docks'] = data['value']
> +                if data['key'] == 'NbBikes': final_point_data['bikes'] = data['value']
> +                if data['key'] == 'NbEmptyDocks': final_point_data['spaces'] = data['value']
> +                val_addon = tuple(final_addon_data.values())
>
> This is not a good approach - this is not validating the order in which
> the tuple is generated
> ------------------------------
>
> In DDL.sql
> <https://github.com/wealth42/nick-fury/pull/11#discussion_r446262899>:
>
> > +drop table if exists addons;
> +CREATE TABLE IF NOT EXISTS `point` (
> +	`id` VARCHAR(300) unique,
> +	`url` VARCHAR(300) NULL,
> +	`commonName` VARCHAR(300) NULL,
> +	`placeType` VARCHAR(300) NULL,
> +	`children` JSON NULL,
> +	`childrenUrls` JSON NULL,	
> +	`lat` FLOAT NULL,
> +	`lon` FLOAT NULL,
> +	`bikes` int NULL,
> +	`spaces` int NULL,
> +	`docks` int NULL,
> +	  CONSTRAINT prkey1 PRIMARY KEY (id)
> +);
> +CREATE TABLE IF NOT EXISTS `addons` (
>
> Since you have already stored the data for bike availability in the
> 'point' table, this table might be redundant.
> ------------------------------
>
> In bikepoint.py
> <https://github.com/wealth42/nick-fury/pull/11#discussion_r446263731>:
>
> > +                if data['key'] == 'NbBikes': final_point_data['bikes'] = data['value']
> +                if data['key'] == 'NbEmptyDocks': final_point_data['spaces'] = data['value']
> +                val_addon = tuple(final_addon_data.values())
> +                cursor.execute(sql_addons, val_addon)
> +
> +            val_point = tuple(final_point_data.values())
> +            cursor.execute(sql_point, val_point)
> +        db.commit()
> +        print(cursor.rowcount, "record inserted.")
> +        db.close()
> +
> +    except mysql.connector.Error as err:
> +        print('found error', err)
> +
> +
> +def looper():
>
> Try replacing this with crontab instead
> ------------------------------
>
> In query.py
> <https://github.com/wealth42/nick-fury/pull/11#discussion_r446264757>:
>
> > @@ -0,0 +1,21 @@
> +import mysql.connector
> +
> +def script(s):
> +    try:
> +        db = mysql.connector.connect(user='', password='',#user & #password
> +                                     host='127.0.0.1', database="bikepoint")
> +        cursor = db.cursor()
> +        querry='SELECT * FROM bikepoint.point where commonName like \'%{query}%\';'
>
> Avoid using incorrect and ambiguous spellings - creates space for very
> difficult to find problems later
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wealth42/nick-fury/pull/11#pullrequestreview-438400236>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOXVBYKHZCL55HLKSGDMYWLRYS74FANCNFSM4OJDB5JQ>
> .
>

2020-06-27 13:25 UTC, namangulati22 commented
Sir/Ma'am,
The pointer that you gave me for the file, bikepoint.py which quotes that :
"This is not a good approach - this is not validating the order in which
the tuple is generated"
I am not able to understand this one. Can you please help me with this by
being more specific?

I am able to work on and correct the other problems but this. I request you
to help me ASAP so that I can submit the assignment at the earliest.
Thank you

On Fri, Jun 26, 2020, 9:22 PM dashu2410 <notifications@github.com> wrote:

> *@dashu2410* requested changes on this pull request.
>
> Hi @namangulati22 <https://github.com/namangulati22>
> Thanks for attempting the assignment! However, there is an error in the
> understanding of the requirements that were given. We'll be happy to
> reconsider if you can identify and fix the error and re-submit the
> requested changes.
> ------------------------------
>
> In bikepoint.py
> <https://github.com/wealth42/nick-fury/pull/11#discussion_r446261044>:
>
> > +
> +            additional_properties = (final_point_data.pop('additionalProperties')[1:-2].split('}, '))
> +
> +            final_point_data.pop('$type')
> +            for addon in additional_properties:
> +                final_addon_data = dict()
> +                final_addon_data['id'] = final_point_data['id']
> +                data = json.loads(addon + '}')
> +                for key in data:
> +                    final_addon_data[key] = data[key]
> +
> +                final_addon_data.pop('$type')
> +                if data['key'] == 'NbDocks': final_point_data['docks'] = data['value']
> +                if data['key'] == 'NbBikes': final_point_data['bikes'] = data['value']
> +                if data['key'] == 'NbEmptyDocks': final_point_data['spaces'] = data['value']
> +                val_addon = tuple(final_addon_data.values())
>
> This is not a good approach - this is not validating the order in which
> the tuple is generated
> ------------------------------
>
> In DDL.sql
> <https://github.com/wealth42/nick-fury/pull/11#discussion_r446262899>:
>
> > +drop table if exists addons;
> +CREATE TABLE IF NOT EXISTS `point` (
> +	`id` VARCHAR(300) unique,
> +	`url` VARCHAR(300) NULL,
> +	`commonName` VARCHAR(300) NULL,
> +	`placeType` VARCHAR(300) NULL,
> +	`children` JSON NULL,
> +	`childrenUrls` JSON NULL,	
> +	`lat` FLOAT NULL,
> +	`lon` FLOAT NULL,
> +	`bikes` int NULL,
> +	`spaces` int NULL,
> +	`docks` int NULL,
> +	  CONSTRAINT prkey1 PRIMARY KEY (id)
> +);
> +CREATE TABLE IF NOT EXISTS `addons` (
>
> Since you have already stored the data for bike availability in the
> 'point' table, this table might be redundant.
> ------------------------------
>
> In bikepoint.py
> <https://github.com/wealth42/nick-fury/pull/11#discussion_r446263731>:
>
> > +                if data['key'] == 'NbBikes': final_point_data['bikes'] = data['value']
> +                if data['key'] == 'NbEmptyDocks': final_point_data['spaces'] = data['value']
> +                val_addon = tuple(final_addon_data.values())
> +                cursor.execute(sql_addons, val_addon)
> +
> +            val_point = tuple(final_point_data.values())
> +            cursor.execute(sql_point, val_point)
> +        db.commit()
> +        print(cursor.rowcount, "record inserted.")
> +        db.close()
> +
> +    except mysql.connector.Error as err:
> +        print('found error', err)
> +
> +
> +def looper():
>
> Try replacing this with crontab instead
> ------------------------------
>
> In query.py
> <https://github.com/wealth42/nick-fury/pull/11#discussion_r446264757>:
>
> > @@ -0,0 +1,21 @@
> +import mysql.connector
> +
> +def script(s):
> +    try:
> +        db = mysql.connector.connect(user='', password='',#user & #password
> +                                     host='127.0.0.1', database="bikepoint")
> +        cursor = db.cursor()
> +        querry='SELECT * FROM bikepoint.point where commonName like \'%{query}%\';'
>
> Avoid using incorrect and ambiguous spellings - creates space for very
> difficult to find problems later
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wealth42/nick-fury/pull/11#pullrequestreview-438400236>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOXVBYKHZCL55HLKSGDMYWLRYS74FANCNFSM4OJDB5JQ>
> .
>

2020-07-08 14:37 UTC, closed without merging