Project Of My Choice HTML CSS
wealth42/nick-fury pull request #41
Opened 2020-09-26 14:25 UTC by GauravPatil8778

# Gaurav Patil

## Please check if the PR fulfills these requirements
- [ ] The commit message follows [best practices](https://github.community/t/best-practices-for-pull-requests/10195)
- [ ] Proper `documentation` has been added
- [ ] `Steps to run the project` have been included in the README
- [ ] No `binaries/compressed` files have been added
- [ ] Removed pre-existing assignment `README` files
- [ ] `Screenshots` have been added to the screenshots folder (optional for backend code)

## Breifly write about the project that you have submitted from the perspective of the user.

## Assumptions you have made for this project?

## Other information (like testing credentials)

## Did you learn anything new while doing this assignment? Please explain.

## How much time did it take for you complete the project?

## What was your motivation behind choosing this evaluation mode and project?

2020-09-26 14:26 UTC, GauravPatil8778 commented
Here i Uploaded # projects in HTML CSS as I received message through INTERNSHALA chat

2020-09-26 14:26 UTC, GauravPatil8778 commented
Extract these files to see.

2020-09-28 06:33 UTC, pradnyalgandhi requested changes

2020-09-28 06:33 UTC, pradnyalgandhi commented on README.md
> +Step 1 - extact zip file
Please upload the code of the project and not a zip file.

2020-09-28 12:31 UTC, closed without merging